#______  _    _______  ______                _                 _              
#| ___ \| |  | | ___ \ | ___ \              | |               (_)             
#| |_/ /| |  | | |_/ / | |_/ /__ _ _ __   __| | ___  _ __ ___  _ _______ _ __ 
#| ___ \| |/\| |  __/  |    // _` | '_ \ / _` |/ _ \| '_ ` _ \| |_  / _ \ '__|
#| |_/ /\  /\  / |     | |\ \ (_| | | | | (_| | (_) | | | | | | |/ /  __/ |   
#\____/  \/  \/\_|     \_| \_\__,_|_| |_|\__,_|\___/|_| |_| |_|_/___\___|_|   
#
# Gamemodes:
#   Bed Bridge Fight
#   Four Way Bridge Fight
#   Competitive Bridge
#   Obstacle
#   Sumo
#   Sumo Duels
#   Ground Duel
#   Resource Collect
#   Old Resource Collect
#   Void Fight
#   Stick Fight
#   Party Games
#   Beta Sumo
#   Bow Fight
#   Pearl Fight
#   Bed Rush
#   Ladder Fight
#   Flat Fight
#   Bedwars Normal
#   Bedwars Late Game
#   Bedwars Mega
#   Bedwalls
#   Ranked Fours Practice
#   Bedwars Eight Team
#   Bedwars Four Team
#   Miniwars
#   Bedwars Rush Duels
#   Sky Conquer
#   Autobox
#

import random

# CONFIG
gamemode = "Ladder Fight" # Pick a gamemode from above
playerrank = "Master" # Your rank should either be "Member", "Adept", "Expert", and "Master" (Anyone above just use Master)

# CODE
rowsperpage = 4
itemsperrow = 9

if gamemode == "Bed Bridge Fight":
    fullpages = 1
    lastpage_fullrows = 3
    lastrow_items = 6
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Tool Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Use old maps", "rank":"Adept"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Four Way Bridge Fight":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Use old maps", "rank":"Adept"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Competitive Bridge":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 4
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Obstacle":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 7
    itemdefs = [
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Obstacles Side Walls"},
        {"name":"Obstacles Roof"},
        {"name":"Number of Obstacle Segments"},
        {"name":"Win Condition"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Sumo":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 8
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Infinite Rail Gun", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"},
        {"name":"Spooky Mode", "rank":"Adept"},
        {"name":"Merry Mode", "rank":"Adept"}
    ]
elif gamemode == "Sumo Duels":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Ground Duel":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 4
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Resource Collect":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Emerald Requirement"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Old Resource Collect":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Emerald Requirement"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Void Fight":
    fullpages = 1
    lastpage_fullrows = 3
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Tool Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Stick Fight":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Party Games":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 4
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Beta Sumo":
    fullpages = 1
    lastpage_fullrows = 2
    lastrow_items = 0
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Infinite Rail Gun", "rank":"Master"},
        {"name":"Infinite Thor Hammer", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Use old charge mechanic", "rank":"Expert"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Starting Level", "rank":"Adept"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Bow Fight":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Pearl Fight":
    fullpages = 1
    lastpage_fullrows = 1
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Number of Lives"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Bed Rush":
    fullpages = 1
    lastpage_fullrows = 3
    lastrow_items = 6
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Tool Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Bed Rush Size", "rank":"Adept"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Ladder Fight":
    fullpages = 1
    lastpage_fullrows = 3
    lastrow_items = 5
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Tool Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"}
    ]
elif gamemode == "Bedwars 4 Teams":
    fullpages = 2
    lastpage_fullrows = 0
    lastrow_items = 4
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Emerald Gen Speed", "rank":"Adept"},
        {"name":"Diamond Gen Speed", "rank":"Adept"},
        {"name":"Starting Diamonds", "rank":"Adept"},
        {"name":"Forge Speed", "rank":"Adept"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Mob Shop Items", "rank":"Expert"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"OP Generators", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"},
        {"name":"Allow Projectiles", "rank":"Adept"},
        {"name":"Increased Diamond Costs", "rank":"Adept"},
        {"name":"Convert Eight-team Maps", "rank":"Master"}
    ]
elif gamemode == "Bedwars 8 Teams":
    fullpages = 2
    lastpage_fullrows = 0
    lastrow_items = 4
    itemdefs = [
        {"name":"Wool Count"},
        {"name":"Knockback Stick", "rank":"Adept"},
        {"name":"Bow"},
        {"name":"Arrows"},
        {"name":"Use shears"},
        {"name":"Ender Pearls", "rank":"Expert"},
        {"name":"Sword Tier"},
        {"name":"Sword Sharpness"},
        {"name":"Armour Tier"},
        {"name":"Ladders", "rank":"Adept"},
        {"name":"Fireballs", "rank":"Adept"},
        {"name":"TNT", "rank":"Adept"},
        {"name":"Random Item Bonus", "rank":"Master", "note":"I actually have no clue what this does, if you can tell me, that would be great."},
        {"name":"Bridge Eggs", "rank":"Expert"},
        {"name":"Iron Golems", "rank":"Expert"},
        {"name":"Fishing Rods", "rank":"Adept"},
        {"name":"Snow Balls / Silverfish", "rank":"Adept"},
        {"name":"Juke Box", "rank":"Master"},
        {"name":"Pop up towers", "rank":"Expert"},
        {"name":"Fireball Bow", "rank":"Master"},
        {"name":"Rapid Fire", "rank":"Master"},
        {"name":"Aimbot", "rank":"Master"},
        {"name":"Emerald Gen Speed", "rank":"Adept"},
        {"name":"Diamond Gen Speed", "rank":"Adept"},
        {"name":"Starting Diamonds", "rank":"Adept"},
        {"name":"Forge Speed", "rank":"Adept"},
        {"name":"Golden Apple on Kill", "rank":"Expert"},
        {"name":"Summon ender dragon on Start", "rank":"Master"},
        {"name":"Ender Dragon Block Destruction"},
        {"name":"Combo PVP (no hit delay)", "rank":"Master", "note":"Don't stand in fire"},
        {"name":"Respawn Length"},
        {"name":"Instant Block Break", "rank":"Adept"},
        {"name":"Allow Map to be Broken", "rank":"Master"},
        {"name":"Allow Placements Anywhere", "rank":"Master"},
        {"name":"Double Jump", "rank":"Expert"},
        {"name":"Double Jump Power", "rank":"Master"},
        {"name":"Kill Effects", "rank":"Expert"},
        {"name":"Rising Lava", "rank":"Master"},
        {"name":"Falling anvils", "rank":"Master"},
        {"name":"Random Enderpearls", "rank":"Master"},
        {"name":"Random MLG Clutch", "rank":"Master"},
        {"name":"MLG Clutch Mode", "rank":"Master"},
        {"name":"Random TNT Spawns", "rank":"Master"},
        {"name":"Chicken Head", "rank":"Master"},
        {"name":"OP Shop Items", "rank":"Master"},
        {"name":"Mob Shop Items", "rank":"Expert"},
        {"name":"Wool Allergy", "rank":"Master"},
        {"name":"OP Generators", "rank":"Master"},
        {"name":"Random Potion Effects", "rank":"Master"},
        {"name":"Timed Effects", "rank":"Master"},
        {"name":"Random Health", "rank":"Master"},
        {"name":"Random Health Range", "rank":"Master"},
        {"name":"Desync Health", "rank":"Master"},
        {"name":"Life Steal", "rank":"Expert", "note":"Due to bugs, this option can cause softlocks when a player runs out of hearts before their bed is destroyed. They will count as alive even though they have been long since been Final killed. ENABLE AT YOUR OWN RISK."},
        {"name":"Bed Defence", "rank":"Adept"},
        {"name":"Elemental Bedwars", "rank":"Master"},
        {"name":"Click Reducer"},
        {"name":"Allow Crafting", "rank":"Master"},
        {"name":"Random Block Placing", "rank":"Adept", "note":"Good luck placing blocks"},
        {"name":"Random Item Drops", "rank":"Adept"},
        {"name":"Random Item On Kill", "rank":"Adept"},
        {"name":"XP Level"},
        {"name":"Allow Armour Swapping"},
        {"name":"Create bedrock walls", "rank":"Master", "note":"Set it to 1 minute or disable if already set to 1 minute. DO NOT SET IT TO 20 MINUTES, YOU WILL NOT BE ABLE TO DO ANYTHING."},
        {"name":"Explosion Power", "rank":"Expert"},
        {"name":"Jump Boost Effect", "rank":"Adept"},
        {"name":"Speed Effect", "rank":"Adept"},
        {"name":"Blindness Effect", "rank":"Expert"},
        {"name":"Health", "rank":"Expert"},
        {"name":"Fall Damage"},
        {"name":"Spawn protection time"},
        {"name":"Allow Chat"},
        {"name":"Start game tweak message"},
        {"name":"Kill Messages"},
        {"name":"Allow Projectiles", "rank":"Adept"},
        {"name":"Increased Diamond Costs", "rank":"Adept"}
    ]
else: # Loaded Nothing
    print(f"'{gamemode}' is not a valid gamemode")
    exit()

totalitems = (fullpages*rowsperpage*itemsperrow)+(lastpage_fullrows*itemsperrow)+(lastrow_items)

while True:
    randomvalue = random.randint(1, totalitems)
    try:
        if itemdefs[randomvalue-1]["rank"] == "Member":
            break 
        elif itemdefs[randomvalue-1]["rank"] == "Adept" and (playerrank == "Adept" or playerrank == "Expert" or playerrank == "Master"):
            break
        elif itemdefs[randomvalue-1]["rank"] == "Expert" and (playerrank == "Expert" or playerrank == "Master"):
            break
        elif itemdefs[randomvalue-1]["rank"] == "Master" and playerrank == "Master":
            break
        else:
            try:
                print(f"Rolled {randomvalue} ({itemdefs[randomvalue-1]["name"]}) but player doesn't have a sufficient rank.")
            except IndexError:
                print(f"Rolled {randomvalue} but player doesn't have a sufficient rank.")
    except IndexError:
        break
    except KeyError:
        break
randomitem = randomvalue
randomrow = 1
randompage = 1


while randomitem > itemsperrow:
    randomitem -= itemsperrow
    randomrow += 1
while randomrow > rowsperpage:
    randomrow -= rowsperpage
    randompage += 1

print(f"#{randomvalue} in {gamemode}")
print()
print(f"Page: {randompage}")
print(f"Row: {randomrow}")
print(f"Item: {randomitem}")
print()
try:
    print(itemdefs[randomvalue-1]["name"])
    try:
        print(f"NOTE: {itemdefs[randomvalue-1]["note"]}")
    except KeyError:
        pass
except IndexError:
    print(f"ERROR: ITEM DEFINITION NOT FOUND ({randomvalue})")
    print(f"Gamemode: {gamemode}")
    print(f"Player Rank: {playerrank}")
    print("Item Definition Dump:")
    print(itemdefs)